# (A part of Big Data Analysis)

# The Weather Dataset
Here the Weather Dataset is time series dataset with per-hour information above the weather conditions at a perticular location. It records the Temperature, Dew Point, Relative Humidity, Wind Speed, Presure and Contions.

In [17]:
import pandas as pd

In [18]:
data = pd.read_csv(r"D:\DataAnalysis_Numpy\1. Weather Data.csv")

In [ ]:
data

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

# How to Analyze DataFrames?

# .head()
it shows the first N rows in the data (by default, N=5)

In [16]:
data.head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog

# .shape
Check the number of rows and columns of the dataframe

In [20]:
data.shape

(8784, 8)

# .index
This attribute provides the index of dataframe

In [23]:
data.index

RangeIndex(start=0, stop=8784, step=1)

# .columns 
It show the name of each column

In [24]:
data.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather'],
      dtype='str')

# .dtypes
It shows the data type of each column

In [26]:
data.dtypes

Date/Time               str
Temp_C              float64
Dew Point Temp_C    float64
Rel Hum_%             int64
Wind Speed_km/h       int64
Visibility_km       float64
Press_kPa           float64
Weather                 str
dtype: object

# .unique()
In a column it shows all the unique values. It can be applied on single column only not on the whole datafram

In [27]:
data['Weather'].unique()

<StringArray>
[                                    'Fog',
                    'Freezing Drizzle,Fog',
                           'Mostly Cloudy',
                                  'Cloudy',
                                    'Rain',
                            'Rain Showers',
                            'Mainly Clear',
                            'Snow Showers',
                                    'Snow',
                                   'Clear',
                       'Freezing Rain,Fog',
                           'Freezing Rain',
                        'Freezing Drizzle',
                               'Rain,Snow',
                           'Moderate Snow',
                   'Freezing Drizzle,Snow',
               'Freezing Rain,Snow Grains',
                       'Snow,Blowing Snow',
                            'Freezing Fog',
                                    'Haze',
                                'Rain,Fog',
                             'Drizzle,Fog',
                                 'Drizzle',
                   'Freezing Drizzle,Haze',
                      'Freezing Rain,Haze',
                               'Snow,Haze',
                                'Snow,Fog',
                        'Snow,Ice Pellets',
                               'Rain,Haze',
                      'Thunderstorms,Rain',
              'Thunderstorms,Rain Showers',
        'Thunderstorms,Heavy Rain Showers',
          'Thunderstorms,Rain Showers,Fog',
                           'Thunderstorms',
                  'Thunderstorms,Rain,Fog',
 'Thunderstorms,Moderate Rain Showers,Fog',
                        'Rain Showers,Fog',
               'Rain Showers,Snow Showers',
                            'Snow Pellets',
                           'Rain,Snow,Fog',
                       'Moderate Rain,Fog',
           'Freezing Rain,Ice Pellets,Fog',
                 'Drizzle,Ice Pellets,Fog',
                            'Drizzle,Snow',
                        'Rain,Ice Pellets',
                        'Drizzle,Snow,Fog',
                        'Rain,Snow Grains',
                   'Rain,Snow,Ice Pellets',
                        'Snow Showers,Fog',
              'Moderate Snow,Blowing Snow']
Length: 50, dtype: str

# .nunique()
It show the total nummber of unique values in each column. It can be applied on single column as well as whole dataframe.

In [28]:
data.nunique()

Date/Time           8784
Temp_C               533
Dew Point Temp_C     489
Rel Hum_%             83
Wind Speed_km/h       34
Visibility_km         24
Press_kPa            518
Weather               50
dtype: int64